language: node_js

node_js: "lts/*"

install:
  - yarn

before_install:
  - mkdir release

script:
  - npm run format:check
  - npm run release

deploy:
  provider: releases
  api_key:
    secure: lxDqLR2WT0Z1LyPaxebU7QVI9aUl0qr1tfXD+5oS8bTojyeEEh+G7q4nx+fue1GWAWf2Vzjvc2ZsVoGnu1B/82CjiWCy1Inmx2e/A+chmlh6kDjJT1iuk1FUO/isitKjWQ3+P1libuwitnjC/4APhkE6oZItyP3aJXjrIszZojuQaL14ESL0AN8xxd+3rtGrjXBnQPsMzJy8nr6UGKouVneKYEKi/L+PFY999Azq2YCb5rCKnGjOFeFjcdf2J1dFgkLHt1ZV0bUY2gKyxa9tiK+90GLfTtP0ufhjalappuiSFuYMRApImgtE6I41+gW33c42J/dLgXWgtdMMxGARZwKWiInqYuUTXlb29eVMf6R0dET77RuovSfx4TaWcDcWXSGIrFmvharm0OYkWMbQKowQx49LXQydfhQDp0UjcH1EdTu5VIcOGorPPjGbVCci+YtxpasaRa+mwLQJA5Lma/6r+191NQl1NZNEsu8RmCrvyy0QclLa5pyCNdbGh54rcNLdz5P/wNABCI8b4tWPynOJOYWTK1bMyBNl2IWGFT4+wAaGz7fNusOQK5TtLSkX6ZhRLDCCoLUGlA9N74I4/ABu7FssXbDfnhGF0EqKDCn3r1rJOSqc5PeJAn1ziayXVzhoWG/JfvcksOxAcjdwRHWpjf+q5UtBDWfoucqJnN8=
  file: release/radar.zip
  skip_cleanup: true
  on:
    repo: DIYgod/RSSHub-Radar
    tags: true

cache:
  yarn: true
  directories:
    - node_modules