language: node_js

node_js: "lts/*"

install:
  - yarn

before_install:
  - mkdir release

script:
  - npm run format:check
  - npm run release

deploy:
  provider: releases
  api_key:
    secure: ${secure}
  file: release/radar.zip
  skip_cleanup: true
  on:
    repo: DIYgod/RSSHub-Radar
    tags: true

cache:
  yarn: true
  directories:
    - node_modules